### PR TITLE
nodes.yaml: Use runner-2 for main tasks

### PR DESCRIPTION
**Pull request by nuclearcat**
As we are optimizing config, we need to use runner-2 for main tasks

### CODE REVIEW

**Comment by gctucker** [comment]
BTW I think it was more a glitch during the move to the new Azure runners than optimisation, if I remember correctly all the main jobs were already running on the same runner before.

**Comment by nuclearcat** [comment]
I just checked history, main jobs was on two runners, monitor and trigger - kernelci6, runner and complete on kernelci1.

**Comment by gctucker** [comment]
Ah so maybe we didn't need to change the nodes then. Well there should be a reason for doing one or the other

**Comment by nuclearcat** [comment]
I suspect they was separated because zombies issue was causing resource leak (and this is why runners was rebooted on each deploy).

**Comment by gctucker** [comment]
Ah yes, that's why. The test runners need Kubernetes credentials, at least with the previous setup that was the case with some being setup as "snowflakes" and others couldn't use kubectl etc. Now I think they're all the same so we should indeed be able to consolidate that and have them all run on the same runner. It'll be something to keep an eye on during the prod update on Monday with the pipe cleaner job, also we can check by hand that kubectl has everything setup on runner-2 by hand already to smoke test it.

Cc @VinceHillier

**Comment by gctucker** [comment]
Sorry not the test runner jobs, they just talk to LAVA labs with credentials in Jenkins but the kernel build jobs use k8s.

**Pull request merged**
